# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - python -m pip install -U pip setuptools wheel
    install:
      - python -m pip install -U --upgrade-strategy eager --no-cache-dir -r requirements.txt
      - python -m pip install -U --upgrade-strategy eager --no-cache-dir -r docs/requirements.txt
      - python -m pip install -U --upgrade-strategy eager --no-cache-dir .

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/source/conf.py
   fail_on_warning: true
